# Generated by Django 3.2.9 on 2021-12-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinanser', '0006_auto_20211129_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candle_acc_trade_volume', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
