# Generated by Django 3.2.9 on 2022-01-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinanser', '0008_auto_20211215_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawdataKrw1Inch',
            fields=[
                ('date_time', models.DateTimeField(primary_key=True, serialize=False)),
                ('date_time_last', models.DateTimeField(blank=True, null=True)),
                ('opening_price', models.FloatField(blank=True, null=True)),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('low_price', models.FloatField(blank=True, null=True)),
                ('trade_price', models.FloatField(blank=True, null=True)),
                ('candle_acc_trade_price', models.FloatField(blank=True, null=True)),
                ('candle_acc_trade_volume', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rawdata_krw-1inch',
                'managed': False,
            },
        ),
    ]
