# Generated by Django 3.2.9 on 2022-01-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinanser', '0009_rawdatakrw1inch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeResults',
            fields=[
                ('trade_id', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('start_date_time', models.DateTimeField(db_index=True)),
                ('predict_model', models.CharField(max_length=31)),
                ('model_version', models.FloatField()),
                ('market', models.CharField(max_length=15)),
                ('bid_goal', models.FloatField()),
                ('ask_goal', models.FloatField()),
                ('bid_date_time', models.DateTimeField(blank=True, null=True)),
                ('bid_price', models.FloatField(blank=True, null=True)),
                ('bid_volume', models.FloatField(blank=True, null=True)),
                ('bid_trade_price', models.FloatField(blank=True, null=True)),
                ('ask_date_time', models.DateTimeField(blank=True, null=True)),
                ('ask_price', models.FloatField(blank=True, null=True)),
                ('ask_volume', models.FloatField(blank=True, null=True)),
                ('ask_trade_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trade_results',
                'managed': False,
            },
        ),
    ]
