# Generated by Django 3.2.9 on 2022-01-06 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinanser', '0010_traderesults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traderesults',
            options={},
        ),
    ]
