# Generated by Django 3.2.9 on 2022-01-06 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinanser', '0011_alter_traderesults_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeResults',
        ),
    ]
