# Generated by Django 3.2.9 on 2022-01-06 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinanser', '0013_traderesults'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traderesults',
            old_name='ask_trade_price',
            new_name='ask_funds',
        ),
        migrations.RenameField(
            model_name='traderesults',
            old_name='bid_trade_price',
            new_name='bid_funds',
        ),
    ]
